### ISSUE TITLE
Removed Storage location files still appear in matched/unmatched files

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#373] opened 2020-10-23 13:10 UTC
even after multiple re-scans,

Removed Storage location files still appear in matched/unmatched files

Once a location is deleted/removed from the list, all its files should be removed from database

**Comment by theRealKLH** [comment] 2020-10-23 16:21
this is a duplicate of #141

**Closed** 2020-10-27 21:02 UTC
Labels: duplicate

**Comment by f5kkrs** [comment] 2023-06-06 02:56
> this is a duplicate of #141

This is NOT a duplicate of #141. It's a duplicate of #149. Neither of them are resolved. Both are tagged as duplicates of #141 but they are NOT. This is unresolved.
