### ISSUE TITLE
CzechVRNetwork scrapers do not work properly

### ISSUE THREAD

**Issue by Sinoh726** [xbapps/xbvr#1681] opened 2024-03-31 16:49 UTC
all CzechVRNetwork scrapers do not work since beginning of March

**Comment by Sinoh726** [comment] 2024-03-31 16:55
CzechVRNetwork scrapers do not work properly, dates of scenes are not proper and other issues

**Comment by theRealKLH** [comment] 2024-04-01 19:37
dupe of #1661

**Closed by theRealKLH** 2024-04-01 19:37 UTC

**Comment by theRealKLH** [comment] 2024-04-01 19:38
also resolved by #1672 from last week
