### ISSUE TITLE
Edit tags and cast names

### ISSUE THREAD

**Issue by SpedNSFW** [xbapps/xbvr#303] opened 2020-07-21 20:23 UTC
Some scenes don't get tags added (all of mine from VirtualRealPorn) and some actresses have aliases, for example "Nancy A" and "Nancy Ace" are two that XBVR pick up.

I'd love for two features to be added:

1. Allow the manual editing of scene tags.
2. Allow the editing of cast names on scenes.

**Comment by Aerowen** [comment] 2020-07-24 22:12
Related to #161 but I agree there are lots of tags that are duplicates or have a typo on one site etc. I think the idea for tag and model linking was good, but still I'd like to see XBVR come with a list of tag/model fixes. Ideally with a way to submit them as well. And if submitting is possible, then maybe even to add tags that sites just forget to add as well.

**Comment by SpedNSFW** [comment] 2020-07-24 22:16
Would it not be possible to just grab a model's aliases from a site like indexxx.com?

**Comment by vpfruitly** [comment] 2020-08-11 18:10
Yeah, I think this is a dupe of #161 and I'm going to close it as such. Please comment there to keep the discussion going, I think this is something that's sorely needed.

**Closed by vpfruitly** 2020-08-11 18:10 UTC
